/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.pdfexpedientes;

import dto.AlumnoDTO;
import dto.ReporteDTO;
import dto.ReporteExpedienteDTO;
import fachada.FachadaGenerarReportes;
import fachada.FachadaGestionarIncidencias;
import fachada.IFachadaGenerarReportes;
import fachada.IFachadaGestionarIncidencias;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.EventObject;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.CellEditorListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import presentacion.forms.FrmBandejaEntrada;
import presentacion.forms.FrmValidarReporte;

/**
 *
 * @author Oliver Valle
 */
public class FrmBuscarExpediente extends javax.swing.JFrame {
    
    IFachadaGestionarIncidencias gestionIncidencias ;
    IFachadaGenerarReportes generarReportes ;
    List<AlumnoDTO> alumnos ;
    /**
     * Creates new form FrmBuscarExpediente
     */
    public FrmBuscarExpediente() {
        initComponents();
        gestionIncidencias = new FachadaGestionarIncidencias() ;
        generarReportes = new FachadaGenerarReportes() ;
        alumnos = new ArrayList() ;
    }

    
    
    
    
    
    
    
    
    public void refrescarTabla() {
        
        DefaultTableModel modeloTabla = new DefaultTableModel() ;
        Object[] datosTabla = new Object[4];
        modeloTabla.addColumn("CURP");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Grado y Grupo");
        modeloTabla.addColumn("Expediente");
        
        
        
        for (int i = 0; i < alumnos.size(); i++) {
            datosTabla[0] = alumnos.get(i).getCurp() ;
            datosTabla[1] = alumnos.get(i).getNombre() ;
            datosTabla[2] = alumnos.get(i).getGradoGrupo() ;
            datosTabla[3] = "Ver" ;
            
            
            modeloTabla.addRow(datosTabla);
        }
        
        tablaExpedientes.setModel(modeloTabla);
        tablaExpedientes.setRowHeight(30);
        tablaExpedientes.getColumnModel().getColumn(3).setCellRenderer(new JButtonRenderer("Ver"));
        tablaExpedientes.getColumnModel().getColumn(3).setCellEditor(new JButtonCellEditor("Ver",botonValidar()));

    }
    
    public ActionListener botonValidar() {
        ActionListener validarListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                List<ReporteDTO> reportesAlumno = gestionIncidencias.recuperarReportesAlumno(alumnos.get(tablaExpedientes.getSelectedRow()).getCurp()) ;
                List<ReporteExpedienteDTO> reportesExpedientesAlumno = gestionIncidencias.convertirReportesAReporteExpediente(reportesAlumno) ;
                
                generarReportes.generarReporte(reportesExpedientesAlumno);
                
            }
        } ;
        
        return validarListener ;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        lblGrupo = new javax.swing.JLabel();
        lblGrado = new javax.swing.JLabel();
        comboBoxGrupo = new javax.swing.JComboBox<>();
        comboBoxGrado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaExpedientes = new javax.swing.JTable();
        fondoFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(0, 102, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 120, 40));

        lblGrupo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGrupo.setForeground(new java.awt.Color(0, 0, 0));
        lblGrupo.setText("Grupo");
        getContentPane().add(lblGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        lblGrado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblGrado.setForeground(new java.awt.Color(0, 0, 0));
        lblGrado.setText("Grado");
        getContentPane().add(lblGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        comboBoxGrupo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        comboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "A", "B", "C", "D", "E", "F" }));
        getContentPane().add(comboBoxGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 130, 40));

        comboBoxGrado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        comboBoxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir...", "1", "2", "3" }));
        getContentPane().add(comboBoxGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 130, 40));

        tablaExpedientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CURP", "Nombre", "Grado y Grupo", "Expediente"
            }
        ));
        jScrollPane1.setViewportView(tablaExpedientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 267, 920, 320));

        fondoFrame.setIcon(new javax.swing.ImageIcon("C:\\Users\\omari\\Documents\\GitHub\\Reporte_Escuela_CU1\\ReportesPresentacion\\src\\resources\\busquedaExpedientes.png")); // NOI18N
        getContentPane().add(fondoFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(comboBoxGrado.getSelectedIndex() == 0 && comboBoxGrupo.getSelectedIndex() == 0) {
            JOptionPane.showConfirmDialog(new JFrame(), "Elige un filtro", "Elige un filtro", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE) ;
            return ;
        } else if (comboBoxGrado.getSelectedIndex() != 0 && comboBoxGrupo.getSelectedIndex() == 0){
            alumnos = gestionIncidencias.recuperarAlumnosPorGrado(comboBoxGrado.getSelectedItem().toString()) ;
        } else if(comboBoxGrado.getSelectedIndex() == 0 && comboBoxGrupo.getSelectedIndex() != 0) {
            alumnos = gestionIncidencias.recuperarAlumnosPorGrupo(comboBoxGrupo.getSelectedItem().toString()) ;
        } else {
            alumnos = gestionIncidencias.recuperarAlumnosPorGradoYGrupo(comboBoxGrado.getSelectedItem().toString(), comboBoxGrupo.getSelectedItem().toString()) ;
        }
        
        if(alumnos != null) {
            refrescarTabla() ;
        } else {
            JOptionPane.showConfirmDialog(this, "No hay alumnos en este grado o grupo", "No hay alumnos", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE) ;
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmBuscarExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmBuscarExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmBuscarExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmBuscarExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmBuscarExpediente().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> comboBoxGrado;
    private javax.swing.JComboBox<String> comboBoxGrupo;
    private javax.swing.JLabel fondoFrame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JTable tablaExpedientes;
    // End of variables declaration//GEN-END:variables

    public class JButtonCellEditor implements TableCellEditor {

    private final JButton button;
    private int row;
    private ActionListener actionListener;

    public JButtonCellEditor(String text, ActionListener actionListener) {
        this.button = new JButton(text);
//        this.button.setFont(new Font("Sans Serif", Font.BOLD, 16));
//        this.button.setBackground(new Color(188, 149, 92));
//        this.button.setForeground(new Color(242, 242, 242));
        this.actionListener = actionListener;
        this.button.addActionListener((ActionEvent evt)->{
            this.actionListener.actionPerformed(
                new ActionEvent(this.button, ActionEvent.ACTION_PERFORMED, this.row+"")
            );
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
        this.row = row;
        return this.button;
    }

    @Override
    public Object getCellEditorValue() {
        return true;
    }

    @Override
    public boolean isCellEditable(EventObject anEvent) {
        return true;
    }

    @Override
    public boolean shouldSelectCell(EventObject anEvent) {
        return true;
    }

    @Override
    public boolean stopCellEditing() {
        return true;
    }

    @Override
    public void cancelCellEditing() {}

    @Override
    public void addCellEditorListener(CellEditorListener l) {}

    @Override
    public void removeCellEditorListener(CellEditorListener l) {}
}
    
    public class JButtonRenderer implements TableCellRenderer {

    private final JButton button;

    public JButtonRenderer(String text) {
        this.button = new JButton(text);
//        this.button.setFont(new Font("Sans Serif", Font.BOLD, 16));
//        this.button.setBackground(new Color(188, 149, 92));
//        this.button.setForeground(new Color(242, 242, 242));
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        return this.button;
    }

}               
}


