/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.bdavanzadas.reportespresentacion;

import java.util.Calendar;
import javax.swing.JOptionPane;
import org.itson.bdavanzadas.reportesdominio.NivelIncidencia;
import org.itson.bdavanzadas.reportesdominio.Reporte;
import org.itson.bdavanzadas.reportesdto.ReporteNuevoDTO;
import org.itson.bdavanzadas.reportesnegocios.IFachadaGestionIncidencias;
import org.itson.bdavanzadas.reportespersistencia.IReportesDAO;

/**
 *
 * @author Oliver Valle
 */
public class FrmValidarReporte extends javax.swing.JFrame {

    
    private IFachadaGestionIncidencias gestionIncidencias ;
    private ReporteNuevoDTO reporte ;
    private FotosManager fotosManager;
    
    /**
     * Creates new form FrmValidarReporte
     */
    public FrmValidarReporte(IFachadaGestionIncidencias gestionIncidencias, ReporteNuevoDTO reporte) {
        initComponents();
        this.gestionIncidencias = gestionIncidencias ;
        this.reporte = reporte ;
        this.fotosManager = new FotosManager() ;
        fotoAlumno.setIcon(fotosManager.getFoto(reporte.getAlumno().getUrlFoto()));
        setDatos() ;
    }

    
    private void enableCampos() {
        txtMotivo.setEnabled(true);
        txtMotivo.setEditable(true);
        txtDescripcion.setEnabled(true);
        txtDescripcion.setEditable(true);
        checkLeve.setEnabled(true);
        checkSevero.setEnabled(true);
        checkGrave.setEnabled(true);
    }
    
    private void disableCampos() {
        txtMotivo.setEnabled(false);
        txtMotivo.setEditable(false);
        txtDescripcion.setEnabled(false);
        txtDescripcion.setEditable(false);
        checkLeve.setEnabled(false);
        checkSevero.setEnabled(false);
        checkGrave.setEnabled(false);
    }

    private void setDatos() {
        txtNombre.setText(reporte.getAlumno().getNombre());
        txtApellidoPaterno.setText(reporte.getAlumno().getApellidoP());
        txtApellidoMaterno.setText(reporte.getAlumno().getApellidoM());
        txtCURP.setText(reporte.getAlumno().getCURP());
        txtProfesor.setText(reporte.getDocente().getNombre() + " " + reporte.getDocente().getApellidoP() + " " + reporte.getDocente().getApellidoM());
        txtGrupo.setText(reporte.getAlumno().getGradoGrupo());
        txtMotivo.setText(reporte.getMotivo());
        txtDescripcion.setText(reporte.getDescripcion());
        Calendar fecha = reporte.getFechaHora() ;
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH) + 1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        
        String fechaFormato = año + "/" + mes + "/" + dia;
        txtFecha.setText(fechaFormato);

        
        if (reporte.getNivelIncidencia() == NivelIncidencia.LEVE) {
            checkLeve.setSelected(true);
        } else if(reporte.getNivelIncidencia() == NivelIncidencia.SEVERO) {
            checkSevero.setSelected(true);
        } else {
            checkGrave.setSelected(true) ;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        fotoAlumno = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblCURP = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        checkSevero = new javax.swing.JCheckBox();
        checkGrave = new javax.swing.JCheckBox();
        checkLeve = new javax.swing.JCheckBox();
        lblMotivo = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtProfesor = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnValidar = new javax.swing.JButton();
        toggleModificar = new javax.swing.JToggleButton();
        txtGrupo = new javax.swing.JTextField();
        lblGrupo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        lblProfesor = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtCURP = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        lblApellidos1 = new javax.swing.JLabel();
        lblGrupo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validación de Reporte");
        setMinimumSize(new java.awt.Dimension(1210, 600));
        setPreferredSize(new java.awt.Dimension(1210, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 248, 245));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(155, 90, 23));
        lblTitulo.setText("Validación y Modificación de Reportes");

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(116, 71, 48));
        lblTitulo1.setText("Proyecto EUI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(lblTitulo)
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo1)
                .addGap(438, 438, 438))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 120));

        jPanel3.setBackground(new java.awt.Color(189, 189, 189));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fotoAlumno.setPreferredSize(new java.awt.Dimension(160, 200));
        jPanel3.add(fotoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 200));

        lblNombres.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(0, 0, 0));
        lblNombres.setText("Nombres:");
        jPanel3.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        lblCURP.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblCURP.setForeground(new java.awt.Color(0, 0, 0));
        lblCURP.setText("CURP:");
        jPanel3.add(lblCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        lblApellidos.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidos.setText("Apellido Materno:");
        jPanel3.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        checkSevero.setBackground(new java.awt.Color(255, 255, 255));
        checkSevero.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        checkSevero.setForeground(new java.awt.Color(0, 0, 0));
        checkSevero.setText("Severo");
        checkSevero.setContentAreaFilled(false);
        checkSevero.setEnabled(false);
        checkSevero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSeveroActionPerformed(evt);
            }
        });
        jPanel3.add(checkSevero, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        checkGrave.setBackground(new java.awt.Color(255, 255, 255));
        checkGrave.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        checkGrave.setForeground(new java.awt.Color(0, 0, 0));
        checkGrave.setText("Grave");
        checkGrave.setContentAreaFilled(false);
        checkGrave.setEnabled(false);
        checkGrave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGraveActionPerformed(evt);
            }
        });
        jPanel3.add(checkGrave, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 105, -1));

        checkLeve.setBackground(new java.awt.Color(255, 255, 255));
        checkLeve.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        checkLeve.setForeground(new java.awt.Color(255, 255, 255));
        checkLeve.setText("Leve");
        checkLeve.setContentAreaFilled(false);
        checkLeve.setEnabled(false);
        checkLeve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLeveActionPerformed(evt);
            }
        });
        jPanel3.add(checkLeve, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 85, -1));

        lblMotivo.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblMotivo.setForeground(new java.awt.Color(0, 0, 0));
        lblMotivo.setText("Motivo del Reporte");
        jPanel3.add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFecha.setEnabled(false);
        jPanel3.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 110, 30));

        txtApellidoMaterno.setEditable(false);
        txtApellidoMaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoMaterno.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoMaterno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidoMaterno.setEnabled(false);
        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });
        jPanel3.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 295, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombre.setEnabled(false);
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 295, -1));

        txtProfesor.setEditable(false);
        txtProfesor.setBackground(new java.awt.Color(255, 255, 255));
        txtProfesor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProfesor.setForeground(new java.awt.Color(0, 0, 0));
        txtProfesor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProfesor.setEnabled(false);
        jPanel3.add(txtProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 295, -1));

        lblFecha.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha:");
        jPanel3.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 121, 80, 40));

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, 120, 40));

        btnValidar.setBackground(new java.awt.Color(51, 204, 0));
        btnValidar.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        btnValidar.setForeground(new java.awt.Color(255, 255, 255));
        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        jPanel3.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 120, 40));

        toggleModificar.setBackground(new java.awt.Color(255, 204, 51));
        toggleModificar.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        toggleModificar.setForeground(new java.awt.Color(0, 0, 0));
        toggleModificar.setText("Modificar");
        toggleModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleModificarActionPerformed(evt);
            }
        });
        jPanel3.add(toggleModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 120, 40));

        txtGrupo.setEditable(false);
        txtGrupo.setBackground(new java.awt.Color(255, 255, 255));
        txtGrupo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGrupo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrupo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGrupo.setEnabled(false);
        jPanel3.add(txtGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 70, -1));

        lblGrupo.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblGrupo.setForeground(new java.awt.Color(0, 0, 0));
        lblGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrupo.setText("Nivel de severidad");
        jPanel3.add(lblGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 170, -1));

        txtMotivo.setEditable(false);
        txtMotivo.setBackground(new java.awt.Color(255, 255, 255));
        txtMotivo.setColumns(20);
        txtMotivo.setForeground(new java.awt.Color(0, 0, 0));
        txtMotivo.setRows(5);
        txtMotivo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMotivo.setEnabled(false);
        jScrollPane1.setViewportView(txtMotivo);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 320, 140));

        lblProfesor.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblProfesor.setForeground(new java.awt.Color(0, 0, 0));
        lblProfesor.setText("Profesor:");
        jPanel3.add(lblProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        lblDescripcion.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setText("Descripción");
        jPanel3.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setRows(5);
        txtDescripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(txtDescripcion);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 311, 140));

        txtCURP.setEditable(false);
        txtCURP.setBackground(new java.awt.Color(255, 255, 255));
        txtCURP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCURP.setForeground(new java.awt.Color(0, 0, 0));
        txtCURP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCURP.setEnabled(false);
        jPanel3.add(txtCURP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 295, -1));

        txtApellidoPaterno.setEditable(false);
        txtApellidoPaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoPaterno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidoPaterno.setEnabled(false);
        txtApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoActionPerformed(evt);
            }
        });
        jPanel3.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 295, -1));

        lblApellidos1.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblApellidos1.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidos1.setText("Apellido Paterno:");
        jPanel3.add(lblApellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        lblGrupo1.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblGrupo1.setForeground(new java.awt.Color(0, 0, 0));
        lblGrupo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrupo1.setText("Grupo:");
        jPanel3.add(lblGrupo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 70, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1210, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose() ;
        FrmBandejaEntrada bandejaEntrada = new FrmBandejaEntrada(gestionIncidencias) ;
        bandejaEntrada.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void toggleModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleModificarActionPerformed
        if(toggleModificar.isSelected()) {
            enableCampos() ;
        } else {
            disableCampos() ;
        }
    }//GEN-LAST:event_toggleModificarActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "¿Estás seguro de validar este reporte?. Los cambios que hayan realizados se verán reflejados en el sistema.", "Validar Reporte", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) ;
        NivelIncidencia nivelIncidencia ;
        if (resp == JOptionPane.YES_OPTION) {
            if (checkLeve.isSelected()) {
                nivelIncidencia = NivelIncidencia.LEVE ;
            } else if(checkSevero.isSelected()) {
                nivelIncidencia = NivelIncidencia.SEVERO ;
            } else {
                nivelIncidencia = NivelIncidencia.GRAVE ;
            }
            
            ReporteNuevoDTO reporteNuevo = new ReporteNuevoDTO(reporte.getAlumno(), reporte.getDocente(), nivelIncidencia, txtDescripcion.getText(), txtMotivo.getText(), reporte.getFechaHora(), false, false) ;
            gestionIncidencias.notificarReporte(reporteNuevo) ;
            gestionIncidencias.validarReporte(reporteNuevo) ;
            JOptionPane.showConfirmDialog(this, "¡Se ha validado el Reporte!", "Reporte Validado", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE) ;
            dispose() ;
            FrmBandejaEntrada bandejaEntrada = new FrmBandejaEntrada(gestionIncidencias) ;
            bandejaEntrada.setVisible(true);
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void txtApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaternoActionPerformed

    private void checkGraveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGraveActionPerformed
        if(checkGrave.isSelected()) {
            checkSevero.setSelected(false);
            checkLeve.setSelected(false);
        }
    }//GEN-LAST:event_checkGraveActionPerformed

    private void checkSeveroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSeveroActionPerformed
        if(checkSevero.isSelected()) {
            checkLeve.setSelected(false);
            checkGrave.setSelected(false);
        }
    }//GEN-LAST:event_checkSeveroActionPerformed

    private void checkLeveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLeveActionPerformed
        if(checkLeve.isSelected()) {
            checkSevero.setSelected(false);
            checkGrave.setSelected(false);
        }
    }//GEN-LAST:event_checkLeveActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmValidarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmValidarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmValidarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmValidarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmValidarReporte().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JCheckBox checkGrave;
    private javax.swing.JCheckBox checkLeve;
    private javax.swing.JCheckBox checkSevero;
    private javax.swing.JLabel fotoAlumno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidos1;
    private javax.swing.JLabel lblCURP;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblGrupo1;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblProfesor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JToggleButton toggleModificar;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProfesor;
    // End of variables declaration//GEN-END:variables
}
