/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.bdavanzadas.reportespresentacion;

import java.util.Calendar;
import javax.swing.JOptionPane;
import org.itson.bdavanzadas.reportesdominio.NivelIncidencia;
import org.itson.bdavanzadas.reportesdominio.Reporte;
import org.itson.bdavanzadas.reportesdto.ReporteNuevoDTO;
import org.itson.bdavanzadas.reportesnegocios.IFachadaModificar;
import org.itson.bdavanzadas.reportesnegocios.IFachadaNotificar;
import org.itson.bdavanzadas.reportesnegocios.IFachadaRecuperar;
import org.itson.bdavanzadas.reportesnegocios.IFachadaValidar;
import org.itson.bdavanzadas.reportespersistencia.IReportesDAO;

/**
 *
 * @author Oliver Valle
 */
public class FrmValidarReporte extends javax.swing.JFrame {

    private IFachadaRecuperar fRecuperar ;
    private IFachadaNotificar fNotificar ;
    private IFachadaValidar fValidar ;
    private IFachadaModificar fModificar ;
    private Reporte reporte ;
    private FotosManager fotosManager;
    private IReportesDAO reportesDAO ;
    
    /**
     * Creates new form FrmValidarReporte
     */
    public FrmValidarReporte(IReportesDAO reportesDAO, IFachadaRecuperar fRecuperar, IFachadaNotificar fNotificar, IFachadaValidar fValidar, IFachadaModificar fModificar, Reporte reporte) {
        initComponents();
        this.fRecuperar = fRecuperar ;
        this.fModificar = fModificar ;
        this.fValidar = fValidar ;
        this.fNotificar = fNotificar ;
        this.reporte = reporte ;
        this.fotosManager = new FotosManager() ;
        this.reportesDAO = reportesDAO ;
        fotoAlumno.setIcon(fotosManager.getFoto(reporte.getAlumno().getUrlFoto()));
        setDatos() ;
    }

    
    private void enableCampos() {
        txtMotivo.setEnabled(true);
        txtMotivo.setEditable(true);
        txtDescripcion.setEnabled(true);
        txtDescripcion.setEditable(true);
        checkLeve.setEnabled(true);
        checkSevero.setEnabled(true);
        checkGrave.setEnabled(true);
    }
    
    private void disableCampos() {
        txtMotivo.setEnabled(false);
        txtMotivo.setEditable(false);
        txtDescripcion.setEnabled(false);
        txtDescripcion.setEditable(false);
        checkLeve.setEnabled(false);
        checkSevero.setEnabled(false);
        checkGrave.setEnabled(false);
    }

    private void setDatos() {
        txtNombre.setText(reporte.getAlumno().getNombre());
        txtApellidos.setText(reporte.getAlumno().getApellidoP() + " " + reporte.getAlumno().getApellidoM());
        txtCURP.setText(reporte.getAlumno().getCURP());
        txtProfesor.setText(reporte.getDocente().getNombre() + " " + reporte.getDocente().getApellidoP() + " " + reporte.getDocente().getApellidoM());
        txtGrupo.setText(reporte.getAlumno().getGradoGrupo());
        txtMotivo.setText(reporte.getMotivo());
        txtDescripcion.setText(reporte.getDescripcion());
        Calendar fecha = reporte.getFechaHora() ;
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH) + 1;
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        
        String fechaFormato = año + "/" + mes + "/" + dia;
        txtFecha.setText(fechaFormato);

        
        if (reporte.getNivelIncidencia() == NivelIncidencia.LEVE) {
            checkLeve.setSelected(true);
        } else if(reporte.getNivelIncidencia() == NivelIncidencia.SEVERO) {
            checkSevero.setSelected(true);
        } else {
            checkGrave.setSelected(true) ;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        fotoAlumno = new javax.swing.JLabel();
        lblCURP = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblProfesor = new javax.swing.JLabel();
        checkLeve = new javax.swing.JCheckBox();
        checkSevero = new javax.swing.JCheckBox();
        checkGrave = new javax.swing.JCheckBox();
        lblMotivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        txtCURP = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtProfesor = new javax.swing.JTextField();
        txtGrupo = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnValidar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        toggleModificar = new javax.swing.JToggleButton();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validación de Reporte");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setText("Validación y Modificación de Reportes");

        lblCURP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCURP.setText("CURP:");

        lblNombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombres.setText("Nombres:");

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblApellidos.setText("Apellidos:");

        lblGrupo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrupo.setText("Grupo:");

        lblProfesor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblProfesor.setText("Profesor:");

        checkLeve.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        checkLeve.setText("Leve");
        checkLeve.setEnabled(false);
        checkLeve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLeveActionPerformed(evt);
            }
        });

        checkSevero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        checkSevero.setText("Severo");
        checkSevero.setEnabled(false);
        checkSevero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSeveroActionPerformed(evt);
            }
        });

        checkGrave.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        checkGrave.setText("Grave");
        checkGrave.setEnabled(false);
        checkGrave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGraveActionPerformed(evt);
            }
        });

        lblMotivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMotivo.setText("Motivo del Reporte");

        txtMotivo.setEditable(false);
        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        txtMotivo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMotivo.setEnabled(false);
        jScrollPane1.setViewportView(txtMotivo);

        txtCURP.setEditable(false);
        txtCURP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCURP.setCaretColor(new java.awt.Color(0, 0, 0));
        txtCURP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCURP.setEnabled(false);

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombre.setEnabled(false);

        txtApellidos.setEditable(false);
        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidos.setEnabled(false);

        txtProfesor.setEditable(false);
        txtProfesor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProfesor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProfesor.setEnabled(false);

        txtGrupo.setEditable(false);
        txtGrupo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGrupo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrupo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGrupo.setEnabled(false);

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDescripcion.setText("Descripción");

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(txtDescripcion);

        btnValidar.setBackground(new java.awt.Color(51, 204, 0));
        btnValidar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnValidar.setForeground(new java.awt.Color(255, 255, 255));
        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        toggleModificar.setBackground(new java.awt.Color(255, 204, 0));
        toggleModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        toggleModificar.setForeground(new java.awt.Color(255, 255, 255));
        toggleModificar.setText("Modificar");
        toggleModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleModificarActionPerformed(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha:");

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFecha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFecha.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fotoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombres)
                            .addComponent(lblApellidos)
                            .addComponent(lblCURP)
                            .addComponent(lblProfesor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkLeve, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkSevero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkGrave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblMotivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDescripcion)
                                .addGap(111, 111, 111))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(toggleModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fotoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCURP)
                                    .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombres)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGrupo)
                                .addGap(18, 18, 18)
                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFecha))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblProfesor)
                                    .addComponent(txtProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkLeve)
                        .addGap(18, 18, 18)
                        .addComponent(checkSevero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkGrave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMotivo)
                            .addComponent(lblDescripcion))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnValidar)
                            .addComponent(toggleModificar))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose() ;
        FrmBandejaEntrada bandejaEntrada = new FrmBandejaEntrada(fRecuperar, reportesDAO) ;
        bandejaEntrada.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void toggleModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleModificarActionPerformed
        if(toggleModificar.isSelected()) {
            enableCampos() ;
        } else {
            disableCampos() ;
        }
    }//GEN-LAST:event_toggleModificarActionPerformed

    private void checkLeveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLeveActionPerformed
        if(checkLeve.isSelected()) {
            checkSevero.setSelected(false);
            checkGrave.setSelected(false);
        }
    }//GEN-LAST:event_checkLeveActionPerformed

    private void checkSeveroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSeveroActionPerformed
        if(checkSevero.isSelected()) {
            checkLeve.setSelected(false);
            checkGrave.setSelected(false);
        }
    }//GEN-LAST:event_checkSeveroActionPerformed

    private void checkGraveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGraveActionPerformed
        if(checkGrave.isSelected()) {
            checkSevero.setSelected(false);
            checkLeve.setSelected(false);
        }
    }//GEN-LAST:event_checkGraveActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "¿Estás seguro de validar este reporte?. Los cambios que hayan realizados se verán reflejados en el sistema.", "Validar Reporte", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) ;
        NivelIncidencia nivelIncidencia ;
        if (resp == JOptionPane.YES_OPTION) {
            if (checkLeve.isSelected()) {
                nivelIncidencia = NivelIncidencia.LEVE ;
            } else if(checkSevero.isSelected()) {
                nivelIncidencia = NivelIncidencia.SEVERO ;
            } else {
                nivelIncidencia = NivelIncidencia.GRAVE ;
            }
            
            ReporteNuevoDTO reporteNuevo = new ReporteNuevoDTO(reporte.getAlumno(), reporte.getDocente(), nivelIncidencia, txtDescripcion.getText(), txtMotivo.getText(), reporte.getFechaHora(), false) ;
            fNotificar.notificarReporte(reporteNuevo) ;
            fValidar.validarReporte(reporteNuevo) ;
            JOptionPane.showConfirmDialog(this, "¡Se ha validado el Reporte!", "Reporte Validado", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE) ;
            dispose() ;
            FrmBandejaEntrada bandejaEntrada = new FrmBandejaEntrada(fRecuperar, reportesDAO) ;
            bandejaEntrada.setVisible(true);
        }
    }//GEN-LAST:event_btnValidarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmValidarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmValidarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmValidarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmValidarReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmValidarReporte().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JCheckBox checkGrave;
    private javax.swing.JCheckBox checkLeve;
    private javax.swing.JCheckBox checkSevero;
    private javax.swing.JLabel fotoAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCURP;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblProfesor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JToggleButton toggleModificar;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProfesor;
    // End of variables declaration//GEN-END:variables
}
