/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.iniciarsesion;

import dto.UsuarioDTO;
import excepciones.SubsistemaException;
import fachada.FachadaAdminAcceso;
import fachada.FachadaGestionarIncidencias;
import fachada.IFachadaGestionarIncidencias;
import fachada.IadminAcceso;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import presentacion.forms.FotosManager;

/**
 *
 * @author asielapodaca
 */
public class FrmIniciarSesion extends javax.swing.JFrame {

    private IFachadaGestionarIncidencias gestionIncidencias ;
    private FotosManager fotosManager;
    private IadminAcceso adminAcceso;
    /**
     * Creates new form FrmIniciarSesion
     */
    public FrmIniciarSesion() {
        initComponents();
        setLocationRelativeTo(null);
        iniciarForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_curp = new javax.swing.JTextField();
        psw_pin = new javax.swing.JPasswordField();
        btn_iniciarSesion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_mensajeError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PEINEM_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(137, 21, 71));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 570));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 248, 245));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicia sesión en tu cuenta");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(6, 146, 668, 30);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 248, 245));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¡Hola!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(6, 102, 668, 38);

        txt_curp.setBackground(new java.awt.Color(250, 248, 245));
        txt_curp.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        txt_curp.setMinimumSize(new java.awt.Dimension(400, 50));
        txt_curp.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel1.add(txt_curp);
        txt_curp.setBounds(138, 226, 400, 50);

        psw_pin.setBackground(new java.awt.Color(250, 248, 245));
        psw_pin.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        psw_pin.setMinimumSize(new java.awt.Dimension(400, 50));
        psw_pin.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel1.add(psw_pin);
        psw_pin.setBounds(138, 318, 400, 50);

        btn_iniciarSesion.setBackground(new java.awt.Color(229, 130, 62));
        btn_iniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_iniciarSesion.setText("INICIAR SESIÓN");
        btn_iniciarSesion.setMaximumSize(new java.awt.Dimension(210, 50));
        btn_iniciarSesion.setMinimumSize(new java.awt.Dimension(210, 50));
        btn_iniciarSesion.setPreferredSize(new java.awt.Dimension(210, 50));
        btn_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_iniciarSesion);
        btn_iniciarSesion.setBounds(237, 417, 210, 50);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PIN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(144, 288, 25, 19);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CURP");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(146, 201, 42, 19);

        lbl_mensajeError.setFont(new java.awt.Font("Helvetica Neue", 2, 15)); // NOI18N
        lbl_mensajeError.setForeground(new java.awt.Color(255, 0, 0));
        lbl_mensajeError.setText("NO SE ENCONTRÓ ESTE USUARIO");
        jPanel1.add(lbl_mensajeError);
        lbl_mensajeError.setBounds(138, 374, 244, 19);

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(250, 248, 245));
        jPanel2.setPreferredSize(new java.awt.Dimension(520, 570));
        jPanel2.setSize(new java.awt.Dimension(520, 570));

        PEINEM_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(116, 71, 48));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("incidencias");
        jLabel1.setMaximumSize(new java.awt.Dimension(175, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(175, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(175, 30));
        jLabel1.setSize(new java.awt.Dimension(42, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(116, 71, 48));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¡Bienvenido!");
        jLabel2.setMaximumSize(new java.awt.Dimension(175, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(175, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(175, 30));
        jLabel2.setSize(new java.awt.Dimension(42, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(116, 71, 48));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestor de reportes de");
        jLabel3.setMaximumSize(new java.awt.Dimension(175, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(175, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(175, 30));
        jLabel3.setSize(new java.awt.Dimension(42, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PEINEM_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(PEINEM_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarSesionActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_btn_iniciarSesionActionPerformed

    public void iniciarSesion() {
        try {
            if(txt_curp.getText().isBlank() || psw_pin.getText().isEmpty()) mostrarMensaje();
            
            UsuarioDTO usuario = new UsuarioDTO();
            usuario.setCurp(txt_curp.getText());
            usuario.setPin(psw_pin.getText());
            
            usuario = adminAcceso.iniciarSesion(usuario);
            
            if(usuario == null) {
                mostrarMensaje();
            } else {
                switch(usuario.getRol()) {
                    case "DOCENTE" -> {
                        FrmMenuGeneral frmBuscarEstudiante = new FrmMenuGeneral(usuario);
                        frmBuscarEstudiante.setVisible(true);
                    }
                    case "PREFECTO" -> {
                        FrmMenuGeneral frmBandeja = new FrmMenuGeneral(usuario) ;
                        frmBandeja.setVisible(true);
                    }
                    case "DIRECTIVO" -> {
                        FrmMenuGeneral frmBuscarExpediente = new FrmMenuGeneral(usuario);
                        frmBuscarExpediente.setVisible(true);
                    }
                    default -> System.out.println("El usuario no tiene rol registrado");
                }
                this.dispose();
            }
        } catch (SubsistemaException ex) {
            Logger.getLogger(FrmIniciarSesion.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showConfirmDialog(this, ex.getMessage(), "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE) ;

        }
        
    }
    
    public void mostrarMensaje() {
        lbl_mensajeError.setVisible(true);
    }
    
    private void iniciarForm() {
        this.gestionIncidencias = new FachadaGestionarIncidencias() ;
        insertDatosSimulados();
        this.adminAcceso = new FachadaAdminAcceso();
        lbl_mensajeError.setVisible(false);
        this.fotosManager = new FotosManager() ;
        PEINEM_logo.setIcon(fotosManager.getFoto("src/main/java/presentacion/iniciarsesion/media/PEINEM_logo.png"));
    }
    
    private void insertDatosSimulados() {
        try {
            gestionIncidencias.insertDatosSimulados();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.getMessage(), "Error", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE) ;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PEINEM_logo;
    private javax.swing.JButton btn_iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_mensajeError;
    private javax.swing.JPasswordField psw_pin;
    private javax.swing.JTextField txt_curp;
    // End of variables declaration//GEN-END:variables
}
