/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.iniciarsesion;

import dto.UsuarioDTO;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import presentacion.crearreporte.FrmBuscarEstudiante;
import presentacion.forms.FotosManager;
import presentacion.forms.FrmBandejaEntrada;
import presentacion.pdfexpedientes.FrmBuscarExpediente;

/**
 *
 * @author gamaliel
 */
public class FrmMenuGeneral extends javax.swing.JFrame {

    
    private FotosManager fotosManager;
    private UsuarioDTO usuario;
    /**
     * Creates new form FrmMenuGeneral
     */
    public FrmMenuGeneral(UsuarioDTO usuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuario=usuario;
        fondoFrame();
        botonesImagenes();
        restringirPorRoles();
    }

    private void fondoFrame() {
        this.fotosManager = new FotosManager();
        fondoFrame.setIcon(fotosManager.getFoto("src/main/java/presentacion/iniciarsesion/media/menuGeneral.png"));
    }
    
    private void restringirPorRoles(){
        if (usuario.getRol().equals("DOCENTE")) {
            btnExportar.setEnabled(false);
            btnValidarModificar.setEnabled(false);
        }
        if (usuario.getRol().equals("PREFECTO")) {
            btnCrear.setEnabled(false);
        }
        if (usuario.getRol().equals("DIRECTIVO")) {
            btnCrear.setEnabled(false);
            btnValidarModificar.setEnabled(false);
        }
    }
    
    private void botonesImagenes() {
        this.fotosManager = new FotosManager();

        // Botón "Crear"
        btnCrear.setIcon(fotosManager.getFoto("src/main/java/presentacion/botones/pen-clip.png"));
        btnCrear.setVerticalTextPosition(JButton.BOTTOM);
        btnCrear.setHorizontalTextPosition(JButton.CENTER);
        btnCrear.setText("Crear");

        // Repite este proceso para los demás botones
        // Botón "Validar/Modificar"
        btnValidarModificar.setIcon(fotosManager.getFoto("src/main/java/presentacion/botones/vote-yea.png"));
        btnValidarModificar.setVerticalTextPosition(JButton.BOTTOM);
        btnValidarModificar.setHorizontalTextPosition(JButton.CENTER);
        btnValidarModificar.setText("Validar/Modificar");

        // Botón "Exportar"
        btnExportar.setIcon(fotosManager.getFoto("src/main/java/presentacion/botones/file-export.png"));
        btnExportar.setVerticalTextPosition(JButton.BOTTOM);
        btnExportar.setHorizontalTextPosition(JButton.CENTER);
        btnExportar.setText("Exportar");

        // Cargar la imagen
        ImageIcon iconoOriginal = new ImageIcon("src/main/java/presentacion/botones/cerrar-sesion.png");
        Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
        ImageIcon iconoEscalado = new ImageIcon(imagenEscalada);

        // Establecer el ImageIcon escalado como icono del botón
        btnCerrarSesion.setIcon(iconoEscalado);
        btnCerrarSesion.setVerticalTextPosition(JButton.BOTTOM);
        btnCerrarSesion.setHorizontalTextPosition(JButton.CENTER);
        btnCerrarSesion.setText("Cerrar sesión");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnValidarModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        fondoFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1210, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarSesion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, -1, 80));

        btnExportar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnExportar.setBorder(null);
        btnExportar.setBorderPainted(false);
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 260, 390));

        btnValidarModificar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnValidarModificar.setBorder(null);
        btnValidarModificar.setBorderPainted(false);
        btnValidarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidarModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 260, 390));

        btnCrear.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCrear.setBorder(null);
        btnCrear.setBorderPainted(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 260, 390));
        getContentPane().add(fondoFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        FrmIniciarSesion frmIniciarSesion = new FrmIniciarSesion();
        frmIniciarSesion.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.dispose();
        FrmBuscarEstudiante frmBuscar = new FrmBuscarEstudiante(usuario);
        frmBuscar.setVisible(true);
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnValidarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarModificarActionPerformed
        this.dispose();
        FrmBandejaEntrada frmBandeja = new FrmBandejaEntrada(usuario);
        frmBandeja.setVisible(true);
    }//GEN-LAST:event_btnValidarModificarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        this.dispose();
        FrmBuscarExpediente frmExportar = new FrmBuscarExpediente(usuario);
        frmExportar.setVisible(true);
    }//GEN-LAST:event_btnExportarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnValidarModificar;
    private javax.swing.JLabel fondoFrame;
    // End of variables declaration//GEN-END:variables
}
